// <auto-generated />
using System;
using BaratoInventory.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaratoInventory.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BaratoInventory.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 52, 41, 658, DateTimeKind.Utc).AddTicks(992),
                            Name = "Laptop",
                            Price = 999.99m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 52, 41, 658, DateTimeKind.Utc).AddTicks(993),
                            Name = "Mouse",
                            Price = 25.50m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 3,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 52, 41, 658, DateTimeKind.Utc).AddTicks(994),
                            Name = "Keyboard",
                            Price = 75.00m,
                            Quantity = 30
                        },
                        new
                        {
                            Id = 4,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 52, 41, 658, DateTimeKind.Utc).AddTicks(996),
                            Name = "Monitor",
                            Price = 299.99m,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 5,
                            Category = "Furniture",
                            CreatedAt = new DateTime(2025, 11, 18, 4, 52, 41, 658, DateTimeKind.Utc).AddTicks(997),
                            Name = "Desk Chair",
                            Price = 199.99m,
                            Quantity = 20
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
